GET http://localhost:3001/tugofchore

###
GET http://localhost:3001/tugofchore/63c474788368e494fd507b41

###
POST http://localhost:3001/tugofchore
Content-Type: application/json

{
    "text": "start blue ocean"
}

###
DELETE http://localhost:3001/tugofchore/63c474788368e494fd507b41

###
PATCH http://localhost:3001/tugofchore/complete/63c47906de32e69f683a93e0
