GET http://localhost:3001/tugofchore

###
GET http://localhost:3001/tugofchore/63c391daf877572136377700

###
POST http://localhost:3001/tugofchore
Content-Type: application/json

{
    "text": "ask Hanna for tea"
}

###
DELETE http://localhost:3001/tugofchore/63c391daf877572136377700

###
PUT http://localhost:3001/tugofchore/complete/63bf40f2ebcaf8183b81b3a4
